In [1]:
import numpy as np

In [2]:
# Creating numpy array from a python list
lst = [1,2,3,4,5,6]
arr = np.array(lst)
print(arr)
print(arr.shape) # gives the dimensions of the array
print(arr.dtype)

[1 2 3 4 5 6]
(6,)
int32


In [3]:
print(arr)
arr[0] = 9
print(arr)

[1 2 3 4 5 6]
[9 2 3 4 5 6]


In [4]:
# we can set the dtype of an array for efficient memory management
lst = [9,8,7,6,5,4,3,2,1]
myarr = np.array(lst,np.int8)

In [5]:
print(myarr)

[9 8 7 6 5 4 3 2 1]


In [6]:
print(myarr.dtype)
# More reference on dtype  object
# https://numpy.org/doc/stable/reference/arrays.dtypes.html

int8


In [7]:
myar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myar)
print(myar[0,1]) #  0 th row, 1st column
print(myar.shape) # gives the dimension of the numpy array
print(myarr.dtype) # gives the datatype of the numpy array


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
int8


In [8]:
zero = np.zeros((2,4))  # gives a matrix of dimension 2 X 4 filled with zeros
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
rng = np.arange(10)  # gives a 1d array from 0 to the given range
print(rng)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
linear_space = np.linspace(0,50,10) # gives numbers in between the range that are equally spaced between each 
# and every consecutive number
print(linear_space)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [11]:
emp = np.empty((6,2)) # gives an n X m matrix filled with random numbers(empty matrix)
print(emp)

[[9.60319856e-312 2.47032823e-322]
 [0.00000000e+000 0.00000000e+000]
 [1.10343781e-312 1.31370903e-076]
 [6.81495891e-091 5.64053487e-062]
 [8.26661046e-072 3.40609499e-057]
 [3.99910963e+252 1.90979636e-312]]


In [12]:
iden = np.identity(10)  # returns an identity matrix of n X  n dimensions
print(iden)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [13]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [14]:
z = x.reshape(3,3)  #reshapes the array in the given dimensions(iff n*m == number of elements )
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
z = z.ravel()
print(z)

[0 1 2 3 4 5 6 7 8]


## Axis in numpy


In [16]:
# number of axes in 1d array is 1
# number of axes in 2d array in 2 (the axes along the row is axis0, and the axes along the column is axis1)
print(z)

[0 1 2 3 4 5 6 7 8]


In [17]:
z= z.reshape(3,3)

In [18]:
print(z)
print(z.sum(axis =0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]


In [19]:
print(z.sum(axis = 1))

[ 3 12 21]


In [20]:
transpose = z.T  # Transposes a matrix
print(transpose)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [21]:
z.flat # returns a iterator for a given matrix

In [22]:
for item in z.flat:
    print(item,end=" ")

0 1 2 3 4 5 6 7 8 

In [23]:
z.ndim  # number of dimensions

2

In [24]:
z.size # number of elements

9

In [25]:
z.nbytes  # total bytes consumed by the elements of the array

36

In [26]:
one = np.array([7,9,10,11,63,25,100,120])
print(one)
print(one.argmax())  # returns position of the maximum element
print(one.argmin())  # returns position of the minimum element
print(one.argsort())  # returns position of sorted array w.r.t the original array



[  7   9  10  11  63  25 100 120]
7
0
[0 1 2 3 5 4 6 7]


In [27]:
new = one.reshape(4,2)
print(new)

[[  7   9]
 [ 10  11]
 [ 63  25]
 [100 120]]


In [28]:
print(new.argmax(axis = 0))
print(new.argmax(axis = 1))
print(new.argmin(axis = 0))
print(new.argmin(axis = 1))
print(new.argsort())

[3 3]
[1 1 0 1]
[0 0]
[0 0 1 0]
[[0 1]
 [0 1]
 [1 0]
 [0 1]]


In [29]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
mat2 = np.array([[7,8,9],[4,5,6],[1,2,3]])
print(mat2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [30]:
print(mat+mat2)
print(mat*mat2)

[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]


In [31]:
print(np.sqrt(mat))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [32]:
print(mat.sum())  # sum of all the elements of the matrix
print(mat.min())  # minimum of all elements in the matrix 
print(mat.max()) # maximum of all elements in the matrix
print(np.where(mat<6))
print(np.count_nonzero(mat))  # counts the number of non-zero numbers
mat.itemsize*mat.size  # size of the matrix

45
1
9
(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))
9


36

In [33]:
# https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html